version: "3.8"

services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${TARGET:-dev}
    restart: always
    ports:
      - "5000:5000"
    environment:
      env_file: ./system_configs/.env
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=postgres
    volumes:
      - 'db_data:/var/lib/postgres/data'
volumes:
  db_data:
